language: node_js

node_js:
  - "stable"
  - "10.20.1"

dist: trusty
sudo: false

matrix:
  fast_finish: true

branches:
  only:
    - master
    - develop

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 1
